services:
  # llm:
  #   image: ghcr.io/ggml-org/llama.cpp:server
  #   # image: amperecomputingai/llama.cpp:latest
  #   # command: ./llama-server
  #   ports:
  #     - "6998:6998"
  #   volumes:
  #     - ./models:/app/models
  #     - llm_logs:/var/log
  #   env_file: .env
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 3G
  #       reservations:
  #         memory: 2G
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  # TODO: Figure out how to choose between local build and prebuilt image
  # Uncomment to build the LLM server locally (e.g. for ARM64)
  llm:
    build:
      context: ./llama.cpp
      network: host
    image: local-llm-arm64
    volumes:
      - ./models:/app/models:ro
      - llm_logs:/var/log
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1.5G
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
  whisper:
    build:
      context: ./whisper.cpp
      network: host
    image: local-whisper-arm64
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1.5G
    command:
      [
        "./whisper-server",
        "-m",
        "${WHISPER_MODEL_PATH}",
        "--port",
        "${WHISPER_PORT}",
        "--host",
        "${WHISPER_ARG_HOST}",
      ]
    volumes:
      - ./models:/app/models:ro
      - whisper_logs:/var/log
    restart: unless-stopped
    network_mode: "host"

  url-to-mealie:
    build: ./url-to-mealie
    image: url-to-mealie
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "${URL_TO_MEALIE_ARG_HOST}",
        "--port",
        "${URL_TO_MEALIE_PORT}",
      ]
    volumes:
      - /tmp:/tmp
      - recipe_logs:/var/log
    env_file: .env
    environment:
      - MEALIE_TOKEN=${MEALIE_API_KEY}
      - MEALIE_BASE_URL=${MEALIE_BASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - NO_PROXY=localhost,127.0.0.1
      - no_proxy=localhost,127.0.0.1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"

volumes:
  recipe_logs:
  llm_logs:
  whisper_logs:
